services:
  cbdb-pljava:
    platform: linux/amd64
    image: apache/incubator-cloudberry:cbdb-build-ubuntu22.04-latest
    container_name: cbdb-pljava
    hostname: cdw
    tty: true
    stdin_open: true
    volumes:
      - ../../..:/home/gpadmin/workspace/pljava:rw
      - ../../../../cloudberry:/home/gpadmin/workspace/cloudberry:rw
    ports:
      - "15432:7000"
      - "12222:22"
    command: ["tail", "-f", "/dev/null"]
